name: jaguar_ban_ip
description: Interceptors and functions to filter requests based on IP addresses
version: 0.1.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar: '>=0.5.3 <0.6.0'
  jaguar_ipnet: '>=0.0.1 <0.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  jaguar_reflect: '>=0.5.1 <0.6.0'
